version: '3.8'

services:
  database:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - default.env
    environment:
      POSTGRES_USER: nginx_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: nginx_database
    ports:
      - "5437:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - network

  server:
    container_name: server_container
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - network

  client:
    container_name: client_container
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - network

  nginx:
    container_name: nginx_container
    env_file:
      - default.env
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - "8816:80"
    networks:
      - network

volumes:
  pg_data:
    driver: local

networks:
  network:
    driver: bridge
